import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by Next.js on every build and is not committed.
  { ignores: [".next/**", "node_modules/**", "drizzle/**", "next-env.d.ts"] },
  { rules: { "@typescript-eslint/no-explicit-any": "warn" } },
]

export default config;
