-- Phase 5 (data): seed the Calculations-tab planning as strategies.
-- Matched to existing individuals by the app's sorted-name normalization
-- (ON CONFLICT (normalized_name) DO NOTHING) so no individual is duplicated;
-- planning-only names are created and can be merged later via aliases.
-- Idempotent (NOT EXISTS guards). Rates are read live from program_rate_schedules.

INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('duestch joel', 'Joel Duestch', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('isaac kibudi', 'Isaac Kibudi', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('weiss yoshia', 'Yoshia Weiss', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('brody esther', 'Esther Brody', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('silverman simi', 'Simi Silverman', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('maleh solomon', 'Solomon Maleh', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('fleishman moshe', 'Moshe Fleishman', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('faigy weiss', 'Faigy Weiss', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('fradel ostreicher', 'Fradel Ostreicher', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('chaim goldenberg', 'Chaim Goldenberg', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('berl markowitz', 'Berl Markowitz', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('markowitz shraga', 'Shraga Markowitz', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('brauner leah', 'Leah Brauner', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('mendel stern', 'Mendel Stern', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('moses wagschal', 'Moses Wagschal', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('eizikovitz rivky', 'Rivky Eizikovitz', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('hershel moshkovitz veis', 'Hershel Veis / Moshkovitz', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('breuer yitzchok', 'Yitzchok Breuer', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('frankel tov yom', 'Yom Tov Frankel', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('mier schonbrun', 'Mier Schonbrun', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint
INSERT INTO "individuals" (normalized_name, display_name, status) VALUES ('abraham cohen', 'Abraham Cohen', 'active') ON CONFLICT (normalized_name) DO NOTHING;--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-03-01', 12, 0.23, 0.28, -300.0, 0, 2600.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'duestch joel' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 780.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'duestch joel' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 860.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_COM_HAB' WHERE i.normalized_name = 'duestch joel' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'duestch joel' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 430.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SUPP_GROUP_DAY_HAB' WHERE i.normalized_name = 'duestch joel' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-03-01', 12, 0.24, 0.3, -350.0, 0, 2210.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'isaac kibudi' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 520.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'isaac kibudi' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 780.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'RESPITE' WHERE i.normalized_name = 'isaac kibudi' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 377.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_RESPITE' WHERE i.normalized_name = 'isaac kibudi' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'isaac kibudi' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 500 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SUPP_GROUP_DAY_HAB' WHERE i.normalized_name = 'isaac kibudi' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-01-01', 12, 0.22, 0.22, -125.0, 0, 800.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'weiss yoshia' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'weiss yoshia' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-05-01', 12, 0.24, 0.3, -125.0, 0, 875.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'brody esther' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'brody esther' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 250 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SUPP_GROUP_DAY_HAB' WHERE i.normalized_name = 'brody esther' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-09-01', 12, 0.24, 0.3, 0, 0, 1500.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'silverman simi' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1040.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'silverman simi' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 434.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_COM_HAB' WHERE i.normalized_name = 'silverman simi' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-06-01', 12, 0.24, 0.3, -200.0, 0, 1780.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'maleh solomon' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 416.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'maleh solomon' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 945.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_COM_HAB' WHERE i.normalized_name = 'maleh solomon' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-02-01', 12, 0.24, 0.3, -150.0, 0, 725.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'fleishman moshe' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 520.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'fleishman moshe' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 520.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'RESPITE' WHERE i.normalized_name = 'fleishman moshe' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', NULL, 7, 0.24, 0.3, -125.0, 0, 2280.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'faigy weiss' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'faigy weiss' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 250 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SUPP_GROUP_DAY_HAB' WHERE i.normalized_name = 'faigy weiss' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-01-01', 12, 0.24, 0.3, -100.0, 0, 630.0, 'Account', 1 FROM "individuals" i WHERE i.normalized_name = 'fradel ostreicher' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 780.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'fradel ostreicher' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '2', DATE '2026-01-01', 12, 0.25, 0, -100.0, 0, 1045.0, 'Account', 2 FROM "individuals" i WHERE i.normalized_name = 'fradel ostreicher' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '2');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'fradel ostreicher' AND s.label = '2' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-03-01', 12, 0.24, 0.3, -100.0, 0, 330.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'chaim goldenberg' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 468.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'chaim goldenberg' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', NULL, 12, 0.24, 0.3, -200.0, 0, 1760.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'berl markowitz' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 468.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'berl markowitz' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 780.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'RESPITE' WHERE i.normalized_name = 'berl markowitz' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 156.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_RESPITE' WHERE i.normalized_name = 'berl markowitz' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'berl markowitz' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-01-01', 12, 0.24, 0.3, -200.0, 0, 1830.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'markowitz shraga' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 468.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'markowitz shraga' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 520.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'RESPITE' WHERE i.normalized_name = 'markowitz shraga' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 494.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_RESPITE' WHERE i.normalized_name = 'markowitz shraga' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'markowitz shraga' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-08-01', 12, 0.24, 0.3, -250.0, 0, 0.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'brauner leah' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 686.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_COM_HAB' WHERE i.normalized_name = 'brauner leah' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-06-01', 12, 0.24, 0.3, -100.0, 0, 770.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'mendel stern' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 936.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'mendel stern' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '2', DATE '2025-06-01', 12, 0.24, 0.3, -100.0, 1200.0, 1910.0, 'C', 2 FROM "individuals" i WHERE i.normalized_name = 'mendel stern' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '2');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'mendel stern' AND s.label = '2' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-05-01', 12, 0.24, 0.3, -250.0, 1100.0, 3700.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'moses wagschal' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 480.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'moses wagschal' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 944.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_COM_HAB' WHERE i.normalized_name = 'moses wagschal' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'moses wagschal' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', NULL, 12, 0.24, 0.3, -100.0, 0, 720.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'eizikovitz rivky' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 416.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'RESPITE' WHERE i.normalized_name = 'eizikovitz rivky' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 637.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_RESPITE' WHERE i.normalized_name = 'eizikovitz rivky' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-01-26', 12, 0.24, 0.3, -200.0, 0, 1675.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'hershel moshkovitz veis' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 957.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'hershel moshkovitz veis' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'hershel moshkovitz veis' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 250.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SUPP_GROUP_DAY_HAB' WHERE i.normalized_name = 'hershel moshkovitz veis' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2025-06-01', 12, 0.24, 0.3, -250.0, 0, 1775.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'breuer yitzchok' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1040.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'breuer yitzchok' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 308.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_RESPITE' WHERE i.normalized_name = 'breuer yitzchok' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'breuer yitzchok' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-03-01', 12, 0.24, 0.3, -350.0, 0, 2660.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'frankel tov yom' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 416.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'frankel tov yom' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 520.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'RESPITE' WHERE i.normalized_name = 'frankel tov yom' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 547.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_COM_HAB' WHERE i.normalized_name = 'frankel tov yom' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 388.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SH_RESPITE' WHERE i.normalized_name = 'frankel tov yom' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'frankel tov yom' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 250.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SUPP_GROUP_DAY_HAB' WHERE i.normalized_name = 'frankel tov yom' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-02-01', 12, 0.35, 0.25, -100.0, -150.0, 830.0, 'C', 1 FROM "individuals" i WHERE i.normalized_name = 'mier schonbrun' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'mier schonbrun' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 500 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SUPP_GROUP_DAY_HAB' WHERE i.normalized_name = 'mier schonbrun' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint

INSERT INTO "calculation_strategies" (individual_id, label, renewal_date, month_divisor, cut1_percent, cut2_percent, clock_adjustment, other_adjustment, after_all, account, sort_order) SELECT i.id, '1', DATE '2026-03-13', 12, 0.24, 0.3, -200.0, 0, 1525.0, 'c', 1 FROM "individuals" i WHERE i.normalized_name = 'abraham cohen' AND NOT EXISTS (SELECT 1 FROM "calculation_strategies" s WHERE s.individual_id = i.id AND s.label = '1');--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 780.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'COM_HAB' WHERE i.normalized_name = 'abraham cohen' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 1075.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'DAY_HAB' WHERE i.normalized_name = 'abraham cohen' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);--> statement-breakpoint
INSERT INTO "calculation_strategy_lines" (strategy_id, program_id, authorized_hours) SELECT s.id, p.id, 250.0 FROM "calculation_strategies" s JOIN "individuals" i ON i.id = s.individual_id JOIN "programs" p ON p.code = 'SUPP_GROUP_DAY_HAB' WHERE i.normalized_name = 'abraham cohen' AND s.label = '1' AND NOT EXISTS (SELECT 1 FROM "calculation_strategy_lines" l WHERE l.strategy_id = s.id AND l.program_id = p.id);
