import { generateMonthlyClassDates } from "../../src/lib/business/class-invoicing";
import type { PgLikePool } from "../../src/lib/import/commit";
import {
  createClassActivity,
  createClassBudget,
  createClassInvoiceDraft,
  issueClassInvoice,
} from "../../src/lib/manage/class-invoices";
import {
  E2E_CLASS_ACTIVITY_NAME,
  E2E_CLASS_BUDGET_LABEL,
  E2E_CLASS_DRAFT_INVOICE,
  E2E_CLASS_ISSUED_INVOICE,
  E2E_CLASS_MONTH,
  LINKED_INDIVIDUAL_ID,
} from "./fixtures";

function unwrap<T>(result: { ok: true; data: T } | { ok: false; code: string; message: string }): T {
  if (!result.ok) throw new Error(`${result.code}: ${result.message}`);
  return result.data;
}

/**
 * Seed one production-shaped issued invoice and one editable draft. The PDFs
 * are generated by the application itself, so this acceptance path needs no
 * Vercel Blob token and does not pretend that private storage was exercised.
 */
export async function seedClassDocumentAcceptanceData(pool: PgLikePool, actorId: string): Promise<{
  issuedInvoiceId: string;
  draftInvoiceId: string;
}> {
  const activity = unwrap(await createClassActivity(pool, {
    code: "E2E_CLASS",
    name: E2E_CLASS_ACTIVITY_NAME,
    description: "Disposable browser-acceptance class activity",
    defaultUnitPrice: "150",
    isActive: true,
    sortOrder: 900,
  }, actorId));
  const budget = unwrap(await createClassBudget(pool, {
    individualId: LINKED_INDIVIDUAL_ID,
    label: E2E_CLASS_BUDGET_LABEL,
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    authorizedAmount: "12000",
    notes: "Disposable Classes and Documents browser acceptance",
  }, actorId));
  const lines = generateMonthlyClassDates(E2E_CLASS_MONTH).map((serviceDate) => ({
    activityId: activity.id,
    serviceDate,
  }));
  const common = {
    classBudgetPeriodId: budget.id,
    invoiceDate: "2026-10-01",
    servicePeriodStart: "2026-09-01",
    servicePeriodEnd: "2026-09-30",
    billToName: "Linked Individual",
    billToAddressLine1: "100 Main Street",
    billToAddressLine2: "Apartment 2B",
    billToCityStateZip: "Monroe, NY 10950",
    purpose: "COMMUNITY CLASSES",
    lines,
  };
  const issuedDraft = unwrap(await createClassInvoiceDraft(pool, {
    ...common,
    invoiceNumber: E2E_CLASS_ISSUED_INVOICE,
  }, actorId));
  const issued = unwrap(await issueClassInvoice(pool, issuedDraft.id, actorId));
  const draft = unwrap(await createClassInvoiceDraft(pool, {
    ...common,
    invoiceNumber: E2E_CLASS_DRAFT_INVOICE,
  }, actorId));

  return { issuedInvoiceId: issued.id, draftInvoiceId: draft.id };
}
