import { randomUUID } from 'node:crypto';
import { expect, test, type Page } from '@playwright/test';
import { PDFDocument } from 'pdf-lib';
import { pdfText } from '../support/pdf-text';
import { REPRESENTATIVE_ACCOUNTS, passwordFor, LINKED_INDIVIDUAL_ID, LINKED_EMPLOYEE_ID, E2E_CLASS_ISSUED_INVOICE } from './fixtures';
async function login(page:Page,preset:string){const account=REPRESENTATIVE_ACCOUNTS.find(row=>row.preset===preset)!;await page.context().clearCookies();await page.goto('/signin');await page.getByLabel('Email address').fill(account.email);await page.getByLabel('Password').fill(passwordFor(account));await page.getByRole('button',{name:/^sign in$/i}).click();await page.waitForURL(url=>url.pathname===account.expectedPath);}
test('percentage preview and saved-rule recalculation retry stay distinct',async({page},testInfo)=>{
 await login(page,'owner');let saves=0,refreshes=0;
 await page.route('**/api/agency-financials/employee-terms',async route=>{saves++;const response=await route.fetch();expect(response.status()).toBe(201);await route.fulfill({response,json:{...await response.json(),settlementWarning:'Synthetic isolated refresh failure'}});});
 await page.route('**/api/settlements/refresh',async route=>{refreshes++;await route.continue();});
 await page.goto('/reports/agency-financials?month=2026-09');await page.getByRole('button',{name:'Employee pay rule',exact:true}).click();const dialog=page.getByRole('dialog');
 await dialog.locator('select').nth(0).selectOption(LINKED_EMPLOYEE_ID);await dialog.locator('select').nth(1).selectOption(LINKED_INDIVIDUAL_ID);
 await dialog.getByLabel('Employee share of base (%)').fill('1');await expect(dialog.getByRole('status')).toContainText('the employee receives $10.00');await expect(dialog.getByRole('status')).toContainText('retains $990.00');
 await dialog.getByLabel('Starts',{exact:true}).fill('2026-11-01');await dialog.getByLabel('Reason',{exact:true}).fill('Synthetic percentage boundary review');await dialog.getByRole('button',{name:'Save',exact:true}).click();
 await expect(dialog.getByText('Rule saved; balance refresh failed',{exact:true})).toBeVisible();expect(saves).toBe(1);
 await testInfo.attach('saved-rule-refresh-warning',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
 await dialog.getByRole('button',{name:'Retry balance refresh',exact:true}).click();await expect(dialog).toHaveCount(0);expect(saves).toBe(1);expect(refreshes).toBe(1);
});
test('owner and planner use labeled quantity records while external and staffing roles are denied',async({page},testInfo)=>{
 await login(page,'owner');const programs=await(await page.request.get('/api/programs')).json();const program=programs.data.find((row:{code:string})=>row.code==='COM_HAB');
 const created=await page.request.post('/api/individuals',{data:{displayName:`Quantity Browser ${randomUUID().slice(0,8)}`}});expect(created.status()).toBe(201);const person=(await created.json()).data;
 await page.goto(`/individuals/${person.id}`);await page.getByRole('button',{name:'Add quantity authorization',exact:true}).click();const section=page.locator('section').filter({has:page.getByRole('heading',{name:'Other authorized units',exact:true})});
 await section.getByRole('combobox',{name:'Program',exact:true}).selectOption(program.id);await section.getByLabel('Authorized quantity',{exact:true}).fill('10');await section.getByLabel('Starts',{exact:true}).fill('2026-09-01');await section.getByLabel('Ends / renewal boundary').fill('2026-09-30');await section.getByLabel('Reason',{exact:true}).fill('Synthetic approved visits');await section.getByRole('button',{name:'Save quantity record',exact:true}).click();await expect(section.getByText('Authorized 10 · Used 0 · Remaining 10 visits',{exact:true})).toBeVisible();
 await login(page,'budget_planner');await page.goto(`/individuals/${person.id}`);await section.getByRole('button',{name:'Record completed visits'}).click();await section.getByLabel('Service date',{exact:true}).fill('2026-09-09');await section.getByLabel('Completed visits',{exact:true}).fill('12');await section.getByLabel('Completion evidence reference').fill('Synthetic signed visit log');await section.getByLabel('Reason',{exact:true}).fill('Verified completed visits');await section.getByRole('button',{name:'Save quantity record',exact:true}).click();await expect(section.getByText('Authorized 10 · Used 12 · Remaining -2 visits — Over authorization',{exact:true})).toBeVisible();
 const records=await(await page.request.get(`/api/individuals/${person.id}/quantity-authorizations`)).json();expect(JSON.stringify(records)).not.toMatch(/agencyRate|internalRate|dollars|payroll/);expect(records.data[0]).toMatchObject({remaining:'-2.0000',unitLabel:'visits'});
 await page.setViewportSize({width:390,height:844});await testInfo.attach('quantity-planner-phone',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
 for(const preset of ['individual_parent','staffing_manager','agency_scheduler','custom_access']){await login(page,preset);expect((await page.request.get(`/api/individuals/${person.id}/quantity-authorizations`)).status()).toBe(403);expect((await page.request.post(`/api/individuals/${person.id}/quantity-authorizations`,{data:{action:'consume',agencyRate:999}})).status()).toBe(403);}
});
test('class billing downloads the selected frozen cover after future profile changes',async({page},testInfo)=>{
 await login(page,'class_billing');await page.goto('/classes?month=2026-09');const record=page.getByRole('row').filter({hasText:E2E_CLASS_ISSUED_INVOICE}).first();const link=record.getByRole('link',{name:'Download invoice PDF',exact:true});const href=(await link.getAttribute('href'))!;const id=href.split('/')[4];
 const profilePath=`/api/classes/profiles/${LINKED_INDIVIDUAL_ID}`;expect((await page.request.patch(profilePath,{data:{mailingName:'Frozen Browser Profile A',lifePlanConfirmed:true,addressLine1:'Synthetic original address'}})).ok()).toBe(true);
 expect((await page.request.post(`/api/classes/invoices/${id}/cover-sheet`,{data:{}})).ok()).toBe(true);const frozen=await(await page.request.get(`/api/classes/invoices/${id}/cover-sheet?metadata=1&version=1`)).json();
 expect((await page.request.patch(profilePath,{data:{mailingName:'Future Browser Profile B',lifePlanConfirmed:true,addressLine1:'Synthetic future address'}})).ok()).toBe(true);
 const preview=await page.request.get(`/api/classes/invoices/${id}/cover-sheet?preview=1&version=1`);const output=await page.request.get(`/api/classes/invoices/${id}/cover-sheet?version=1`);expect(preview.status()).toBe(200);expect(output.status()).toBe(200);expect(await pdfText(await preview.body())).toBe(await pdfText(await output.body()));expect(await pdfText(await output.body())).toContain(frozen.data.profile.mailingName);expect(await pdfText(await output.body())).not.toContain('Future Browser Profile B');expect((await PDFDocument.load(await preview.body())).getTitle()).toBe((await PDFDocument.load(await output.body())).getTitle());
 await record.getByRole('button',{name:'Reimbursement cover sheet',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByText('Finalized cover — version 1',{exact:true})).toBeVisible();await expect(dialog.getByLabel('Name',{exact:true})).toHaveValue(frozen.data.profile.mailingName);await expect(dialog.getByLabel('Name',{exact:true})).toBeDisabled();
 const downloadPromise=page.waitForEvent('download');await dialog.getByRole('button',{name:'Cover sheet',exact:true}).click();const download=await downloadPromise;const stream=await download.createReadStream();const chunks:Buffer[]=[];for await(const chunk of stream!)chunks.push(Buffer.from(chunk));const bytes=Buffer.concat(chunks);expect((await PDFDocument.load(bytes)).getTitle()).toContain(E2E_CLASS_ISSUED_INVOICE);expect(await pdfText(bytes)).toContain(frozen.data.profile.mailingName);expect(await pdfText(bytes)).not.toContain('Future Browser Profile B');await testInfo.attach('downloaded-frozen-cover',{body:bytes,contentType:'application/pdf'});await testInfo.attach('frozen-cover-dialog',{body:await page.screenshot({fullPage:true}),contentType:'image/png'});
});
