import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { testPool, resetSchema, truncateBusinessTables, hasTestDatabase, closeTestPool } from "../support/database";
import { createIndividual } from "@/lib/manage/individuals";
import { createClassActivity, createClassBudget, createClassInvoiceDraft, issueClassInvoice, voidClassInvoice } from "@/lib/manage/class-invoices";
import { getClassBudget } from "@/lib/data/class-invoices";
import { createManualIncomeEntry, voidManualIncomeEntry, listManualIncomeEntries } from "@/lib/manage/agency-financials";
import { getAgencyFinancialReport } from "@/lib/data/agency-financial-report";
import { setTransactionsPaid } from "@/lib/manage/transactions";
import { appendClassCoverCorrection, createClassCoverSheetSnapshot, saveClassReimbursementProfile } from "@/lib/manage/class-reimbursement-profiles";
import { getClassCoverVersion, listClassCoverVersions } from "@/lib/data/class-reimbursement-profiles";
import { changeQuantityAuthorization, listQuantityAuthorizations } from "@/lib/manage/quantity-authorizations";
import { createProgramBudget } from "@/lib/manage/program-budgets";
import { buildClassInvoicePdf } from "@/lib/documents/class-invoice-pdf";
import { buildClassCoverSheetPdf } from "@/lib/documents/class-cover-sheet-pdf";
import { PDFDocument } from "pdf-lib";
import { pdfText } from "../support/pdf-text";

const suite=hasTestDatabase?describe:describe.skip;
const ACTOR="00000000-0000-4000-8000-000000000001";
function unwrap<T>(result:{ok:true;data:T}|{ok:false;message:string}):T {if(!result.ok)throw new Error(result.message);return result.data;}
suite("reviewed release controls on disposable PostgreSQL",()=>{
 beforeAll(resetSchema,60_000);afterAll(closeTestPool);
 beforeEach(async()=>{await truncateBusinessTables();await testPool().query("INSERT INTO users(id,email,display_name,password_hash,role) VALUES($1,'owner@synthetic.test','Synthetic Owner','x','admin')",[ACTOR]);});
 async function invoiceFixture(){const pool=testPool();const person=unwrap(await createIndividual(pool,{displayName:"Synthetic Receipt Individual"},ACTOR));
  const budget=unwrap(await createClassBudget(pool,{individualId:person.id,label:"Synthetic 2026",startDate:"2026-01-01",endDate:"2026-12-31",authorizedAmount:"1000"},ACTOR));
  const activity=unwrap(await createClassActivity(pool,{code:"TEST_ACTIVITY",name:"Synthetic Class",defaultUnitPrice:"100"},ACTOR));
  const draft=unwrap(await createClassInvoiceDraft(pool,{classBudgetPeriodId:budget.id,invoiceNumber:"SYNTHETIC-INV-1",invoiceDate:"2026-08-03",servicePeriodStart:"2026-08-01",servicePeriodEnd:"2026-08-31",lines:[{activityId:activity.id,serviceDate:"2026-08-03"}]},ACTOR));
  return{pool,person,budget,invoice:unwrap(await issueClassInvoice(pool,draft.id,ACTOR))};
 }
 it("supports installments, idempotent retry, void/replacement and exactly one allowance use",async()=>{
  const{pool,invoice,budget}=await invoiceFixture();
  expect((await getAgencyFinancialReport(pool,"2026-08")).totals.income.classes).toBe("0.0000");
  const firstInput={requestId:randomUUID(),sourceType:"class" as const,sourceRef:invoice.invoiceNumber,paymentReference:"BANK-TRANSFER-1",serviceDate:"2026-08-02",grossAmount:"50",agencySharePercent:"1"};
  const first=unwrap(await createManualIncomeEntry(pool,firstInput,ACTOR));
  expect(first).toMatchObject({agencyAmount:"0.5000",individualAmount:"49.5000",classInvoiceId:invoice.id});
  expect(unwrap(await createManualIncomeEntry(pool,firstInput,ACTOR)).id).toBe(first.id);
  expect(first.needsPercentageReview).toBe(false);
  await pool.query("UPDATE audit_logs SET metadata=metadata-'percentageInputContract' WHERE action='agency_income.created' AND entity_id=$1",[first.id]);
  const reviewed=(await listManualIncomeEntries(pool)).find(row=>row.id===first.id);expect(reviewed).toMatchObject({needsPercentageReview:true,agencySharePercent:"0.010000",agencyAmount:"0.5000"});
  expect(await createManualIncomeEntry(pool,{...firstInput,grossAmount:"51"},ACTOR)).toMatchObject({ok:false,code:"conflict"});
  expect(await createManualIncomeEntry(pool,{...firstInput,requestId:randomUUID()},ACTOR)).toMatchObject({ok:false,code:"conflict"});
  unwrap(await createManualIncomeEntry(pool,{...firstInput,requestId:randomUUID(),paymentReference:"BANK-TRANSFER-2",grossAmount:"30"},ACTOR));
  unwrap(await voidManualIncomeEntry(pool,first.id,ACTOR,"Wrong first installment amount"));
  const replacementInput={...firstInput,requestId:randomUUID(),replacesEntryId:first.id,grossAmount:"40",notes:"Corrected recorded installment amount"};
  const replacement=unwrap(await createManualIncomeEntry(pool,replacementInput,ACTOR));
  expect(replacement).toMatchObject({replacesEntryId:first.id,sourceRef:invoice.invoiceNumber,paymentReference:"BANK-TRANSFER-1"});
  expect(unwrap(await createManualIncomeEntry(pool,replacementInput,ACTOR)).id).toBe(replacement.id);
  expect((await getAgencyFinancialReport(pool,"2026-08")).totals.income.classes).toBe("70.0000");
  expect(await getClassBudget(pool,budget.id)).toMatchObject({consumedAmount:"100.0000"});
  expect((await pool.query("SELECT id FROM program_budget_events WHERE source_type='agency_manual_income'")).rows).toHaveLength(0);
  expect((await pool.query("SELECT status,void_reason FROM agency_manual_income_entries WHERE id=$1",[first.id])).rows[0]).toMatchObject({status:"void",void_reason:"Wrong first installment amount"});
 });
 it("does not let a legacy replacement claim another void receipt payment identity",async()=>{
  const pool=testPool();const base={sourceType:"other" as const,serviceDate:"2026-08-04",agencySharePercent:"100"};
  const legacy=unwrap(await createManualIncomeEntry(pool,{...base,sourceRef:"LEGACY-PAYMENT",grossAmount:"10"},ACTOR));
  const identified=unwrap(await createManualIncomeEntry(pool,{...base,sourceRef:"OTHER-PAYMENT",paymentReference:"LOCKED-PAYMENT-REF",grossAmount:"20"},ACTOR));
  unwrap(await voidManualIncomeEntry(pool,legacy.id,ACTOR,"Synthetic wrong legacy amount"));unwrap(await voidManualIncomeEntry(pool,identified.id,ACTOR,"Synthetic returned other payment"));
  expect(await createManualIncomeEntry(pool,{...base,sourceRef:"LEGACY-PAYMENT",paymentReference:"LOCKED-PAYMENT-REF",grossAmount:"11",replacesEntryId:legacy.id,notes:"Corrected legacy receipt"},ACTOR)).toMatchObject({ok:false,code:"conflict"});
 });
 it("preserves original cover A after profile B, appends version2 and retrieves VOID facts",async()=>{
  const{pool,person,invoice}=await invoiceFixture();
  const a=unwrap(await saveClassReimbursementProfile(pool,person.id,{mailingName:"Profile A",lifePlanConfirmed:true,addressLine1:"First issued address"},ACTOR));
  unwrap(await createClassCoverSheetSnapshot(pool,invoice.id,a,ACTOR));
  const b=unwrap(await saveClassReimbursementProfile(pool,person.id,{mailingName:"Profile B",addressLine1:"Future address"},ACTOR));
  expect(unwrap(await createClassCoverSheetSnapshot(pool,invoice.id,b,ACTOR)).mailingName).toBe("Profile A");
  expect((await getClassCoverVersion(pool,invoice.id,1))?.addressLine1).toBe("First issued address");
  expect(unwrap(await appendClassCoverCorrection(pool,invoice.id,b,ACTOR,1,"Approved corrected mailing details")).version).toBe(2);
  expect(await appendClassCoverCorrection(pool,invoice.id,b,ACTOR,1,"Stale correction request")).toMatchObject({ok:false,code:"conflict"});
  expect((await listClassCoverVersions(pool,invoice.id)).map(row=>row.version)).toEqual([2,1]);
  const original=await getClassCoverVersion(pool,invoice.id,1);
  expect(original?.mailingName).toBe("Profile A");
  const voided=unwrap(await voidClassInvoice(pool,invoice.id,ACTOR,"Duplicate issued invoice"));
  expect((await PDFDocument.load(await buildClassInvoicePdf(voided))).getTitle()).toBe("VOID - Invoice SYNTHETIC-INV-1");
  expect((await PDFDocument.load(await buildClassCoverSheetPdf(voided,original!))).getTitle()).toBe("VOID - Reimbursement application SYNTHETIC-INV-1");
  expect((await getClassCoverVersion(pool,invoice.id,1))?.mailingName).toBe("Profile A");
  const coverText=await pdfText(await buildClassCoverSheetPdf(voided,original!));expect(coverText).toContain("VOID");expect(coverText).toContain("Profile A");expect(coverText).toContain("Duplicate issued invoice");expect(coverText).not.toContain("Profile B");
 });
 it("makes each Paid change auditable with preserved notes and exact batch retry",async()=>{
  const pool=testPool();const ids=[randomUUID(),randomUUID()];
  await pool.query("INSERT INTO payroll_transactions(id,transaction_fingerprint,is_paid,paid_note) VALUES($1,'synthetic-paid1',false,'Original note'),($2,'synthetic-paid2',true,'Second note')",ids);
  const input={ids,paid:true,batchId:randomUUID(),reason:"Reviewed operator payout status"};
  expect(unwrap(await setTransactionsPaid(pool,input,ACTOR)).updated).toBe(1);
  const audits=await pool.query<{entity_id:string;metadata:{previous:{is_paid:boolean;paid_note:string};next:{is_paid:boolean;paid_note:string;paid_at:string};batchId:string}}>("SELECT entity_id,metadata FROM audit_logs WHERE action='transaction_marked_paid'");
  expect(audits.rows).toHaveLength(1);expect(audits.rows[0]).toMatchObject({entity_id:ids[0],metadata:{batchId:input.batchId,previous:{is_paid:false,paid_note:"Original note"},next:{is_paid:true,paid_note:"Original note"}}});
  expect(audits.rows[0]!.metadata.next.paid_at).toBeTruthy();
  expect(unwrap(await setTransactionsPaid(pool,input,ACTOR)).updated).toBe(1);
  expect(unwrap(await setTransactionsPaid(pool,{ids,paid:true},ACTOR)).updated).toBe(0);
  expect((await pool.query("SELECT id FROM audit_logs WHERE action='transaction_marked_paid'")).rows).toHaveLength(1);
  expect(await setTransactionsPaid(pool,{...input,paid:false},ACTOR)).toMatchObject({ok:false,code:"conflict"});
  await pool.query("ALTER TABLE audit_logs ADD CONSTRAINT reject_paid_audit CHECK(action <> 'transaction_marked_unpaid')");
  await expect(setTransactionsPaid(pool,{ids,paid:false},ACTOR)).rejects.toThrow();
  await pool.query("ALTER TABLE audit_logs DROP CONSTRAINT reject_paid_audit");
  expect((await pool.query<{is_paid:boolean}>("SELECT is_paid FROM payroll_transactions WHERE id=ANY($1::uuid[])",[ids])).rows.every(row=>row.is_paid)).toBe(true);
 });
 it("supports labeled dated quantity revisions, signed usage and reversals without money conversion",async()=>{
  const pool=testPool();const person=unwrap(await createIndividual(pool,{displayName:"Synthetic Visits Individual"},ACTOR));
  const program=(await pool.query<{id:string}>("SELECT id FROM programs WHERE code='COM_HAB'")).rows[0]!.id;
  const input={action:"create",requestId:randomUUID(),programId:program,unitLabel:"visits",authorized:"10",startDate:"2026-08-01",endDate:"2026-08-31",reason:"Approved ten verified visits"};
  const{id}=unwrap(await changeQuantityAuthorization(pool,person.id,input,ACTOR));
  expect(unwrap(await changeQuantityAuthorization(pool,person.id,input,ACTOR)).id).toBe(id);
  const usage={action:"consume",requestId:randomUUID(),id,expectedRevision:1,quantity:"12",serviceDate:"2026-08-12",evidence:"Signed visit record 12",reason:"Verified completion report"};
  unwrap(await changeQuantityAuthorization(pool,person.id,usage,ACTOR));
  expect((await listQuantityAuthorizations(pool,person.id))[0]).toMatchObject({unitLabel:"visits",authorized:"10.0000",used:"12.0000",remaining:"-2.0000"});
  expect(await changeQuantityAuthorization(pool,person.id,{...usage,requestId:randomUUID(),serviceDate:"2026-09-01"},ACTOR)).toMatchObject({ok:false,code:"validation"});
  expect(await changeQuantityAuthorization(pool,person.id,{...usage,requestId:randomUUID(),agencyRate:"99"},ACTOR)).toMatchObject({ok:false,code:"forbidden"});
  const revision={...input,action:"revise",requestId:randomUUID(),id,expectedRevision:1,authorized:"15",reason:"Approved revised fifteen visits"};
  unwrap(await changeQuantityAuthorization(pool,person.id,revision,ACTOR));
  const row=(await listQuantityAuthorizations(pool,person.id))[0]!;
  expect(row).toMatchObject({revision:2,remaining:"3.0000"});expect(row.revisions[0]?.snapshot.authorized_quantity).toBe("10.0000");
  unwrap(await changeQuantityAuthorization(pool,person.id,{action:"reverse",requestId:randomUUID(),id,expectedRevision:2,eventId:row.events[0]!.id,reason:"Completion record entered incorrectly"},ACTOR));
  const after=(await listQuantityAuthorizations(pool,person.id))[0]!;
  expect(after).toMatchObject({used:"0.0000",remaining:"15.0000"});expect(after.events).toHaveLength(2);
  expect((await pool.query("SELECT id FROM payroll_transactions")).rows).toHaveLength(0);
  await expect(pool.query("UPDATE quantity_usage_events SET quantity=1 WHERE authorization_id=$1",[id])).rejects.toThrow(/append-only/);
 });
 it("rejects new non-self-hire individual rates despite legacy override flags",async()=>{
  const pool=testPool();const person=unwrap(await createIndividual(pool,{displayName:"Shared Program Rate Person"},ACTOR));
  const program=(await pool.query<{id:string}>("SELECT id FROM programs WHERE code='COM_HAB'")).rows[0]!.id;
  expect(await createProgramBudget(pool,{individualId:person.id,programId:program,startDate:"2026-01-01",endDate:"2026-12-31",periodType:"custom",authorizedHours:"100",individualRateOverride:"22"},ACTOR)).toMatchObject({ok:false,code:"validation"});
 });
});
