"use client";
import { useState } from "react";
import Link from "next/link";
import type { PriorWorker } from "@/lib/data/prior-workers";
import type { AssignmentRecord } from "@/lib/manage/assignments";
import { agencyDate } from "@/lib/business/agency-time";
export default function PriorWorkers({ individualId, workers, assignments }: { individualId: string; workers: PriorWorker[]; assignments: AssignmentRecord[] }) {
  const [query, setQuery] = useState("");
  const visible = workers.filter((worker) => `${worker.employeeName} ${worker.programName}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <section className="card p-4 sm:p-5"><div className="mb-5 border-b border-[var(--color-rule)] pb-4"><h2 className="font-semibold">Current / future assignments</h2>{assignments.length ? <ul className="mt-2 divide-y divide-[var(--color-rule)]">{assignments.map((assignment) => <li key={assignment.id} className="flex flex-wrap items-center justify-between gap-2 py-2 text-sm"><div>{assignment.employeeName} · {assignment.programName ?? "All programs"}<span className="block text-xs text-[var(--color-ink-soft)]">{assignment.startDate ?? "Open start"} through {assignment.endDate ?? "open end"}{assignment.startDate && assignment.startDate > agencyDate() ? " · Starts later" : " · Current"}</span></div><Link className="text-[var(--color-primary)] underline" href={`/schedule?view=future&individualId=${individualId}&assignmentId=${assignment.id}`}>Open assignment</Link></li>)}</ul> : <p className="mt-2 text-sm text-[var(--color-ink-soft)]">No current or future assignments are recorded.</p>}</div><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Employees who worked with this person</h2><p className="mt-1 text-sm text-[var(--color-ink-soft)]">Recorded service provides context. A current or future assignment is a separate planning decision.</p></div><Link className="btn btn-sm btn-secondary" href={`/schedule?view=future&individualId=${individualId}&newAssignment=1`}>Search other eligible employees</Link></div>
    <input className="input my-3 w-full sm:max-w-sm" type="search" aria-label="Search prior workers" placeholder="Search prior employees or programs" value={query} onChange={(event) => setQuery(event.target.value)} />
    <div className="divide-y divide-[var(--color-rule)]">{visible.map((worker) => {
      const assignment = assignments.find((assignment) => assignment.status === "active" && (!assignment.endDate || assignment.endDate >= agencyDate()) && assignment.employeeId === worker.employeeId && (!assignment.programId || assignment.programId === worker.programId));
      return <div key={`${worker.employeeId}:${worker.programId}`} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-medium">{worker.employeeName}</p><p className="text-xs text-[var(--color-ink-soft)]">{worker.programName} · Latest service: {worker.lastServiceDate ?? "Undated"}</p></div>{!assignment && worker.canCreateAssignment === false ? <span className="text-xs text-[var(--color-ink-soft)]">Inactive employee or program. Search other eligible employees.</span> : <Link className="btn btn-sm btn-secondary" href={`/schedule?view=future&individualId=${individualId}&employeeId=${worker.employeeId}&programId=${worker.programId}&${assignment ? `assignmentId=${assignment.id}` : "newAssignment=1"}`}>{assignment ? "Open existing assignment" : "Create prefilled assignment"}</Link>}</div>;
    })}{!visible.length ? <p className="py-4 text-sm text-[var(--color-ink-soft)]">No prior workers match this view. Search other eligible employees to create an assignment.</p> : null}</div>
  </section>;
}
