"use client";
import { useEffect, useState, type FormEvent } from "react";
import { dec } from "@/lib/money";
import { agencyDate } from "@/lib/business/agency-time";
import type { QuantityAuthorization } from "@/lib/manage/quantity-authorizations";

export default function QuantityAuthorizations({individualId,programs}:{individualId:string;programs:{id:string;name:string;code:string}[]}) {
 const [rows,setRows]=useState<QuantityAuthorization[]>([]);
 const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const [editing,setEditing]=useState<{row:QuantityAuthorization|null;action:"create"|"revise"|"consume"|"reverse";eventId?:string}|null>(null);
 const [saving,setSaving]=useState(false); const [requestId,setRequestId]=useState("");
 const endpoint=`/api/individuals/${individualId}/quantity-authorizations`;
 const load=async()=>{setLoading(true);try{const response=await fetch(endpoint);const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error??"Could not load quantity budgets.");setRows(result.data);setError(null);}catch(error){setError(error instanceof Error?error.message:"Could not load quantity budgets.");}finally{setLoading(false);}};
 useEffect(()=>{let active=true;void fetch(endpoint).then(async response=>{const result=await response.json();if(!active)return;if(!response.ok||!result.ok){setError(result.error??"Could not load quantity budgets.");return;}setRows(result.data);}).catch(()=>{if(active)setError("Could not load quantity budgets.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[endpoint]);
 const open=(row:QuantityAuthorization|null,action:"create"|"revise"|"consume"|"reverse",eventId?:string)=>{setEditing({row,action,eventId});setRequestId(crypto.randomUUID());setError(null);};
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editing)return;setSaving(true);setError(null);const data=Object.fromEntries(new FormData(event.currentTarget));
  try{const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...data,action:editing.action,id:editing.row?.id,expectedRevision:editing.row?.revision,eventId:editing.eventId,requestId})});const result=await response.json();if(!response.ok||!result.ok){setError(result.error??"Could not save this quantity record.");return;}setEditing(null);await load();}catch{setError("Could not reach the server. Your draft is retained; retry uses the same request.");}finally{setSaving(false);}};
 return <section className="card mt-5 p-4 space-y-3">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="display text-lg font-semibold">Other authorized units</h2><p className="text-sm text-[var(--color-ink-soft)]">Visits or other named quantities use verified manual completion records. Hours, money and future schedules remain separate.</p></div><button className="btn btn-sm btn-secondary" type="button" onClick={()=>open(null,"create")}>Add quantity authorization</button></div>
  {error?<p role="alert" className="text-sm text-[var(--color-danger)]">{error} <button type="button" className="underline" onClick={()=>void load()}>Retry loading</button></p>:null}
  {loading?<p role="status">Loading quantity authorizations…</p>:!rows.length?<p className="text-sm text-[var(--color-ink-soft)]">No other quantity authorizations configured.</p>:rows.map(row=><article key={row.id} className="rounded-lg border border-[var(--color-rule)] p-3 space-y-2">
   <div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-semibold">{row.programName} — {row.unitLabel}</h3><p className="text-xs">{row.startDate} through {row.endDate} · Revision {row.revision} · Verified manual quantity</p></div><div className="flex gap-2"><button type="button" className="btn btn-sm btn-secondary" onClick={()=>open(row,"revise")}>Revise authorization</button><button type="button" className="btn btn-sm btn-primary" onClick={()=>open(row,"consume")}>Record completed {row.unitLabel}</button></div></div>
   <p className={`tnum text-sm ${dec(row.remaining).lt(0)?"text-[var(--color-danger)] font-semibold":""}`}>Authorized {dec(row.authorized).toString()} · Used {dec(row.used).toString()} · Remaining {dec(row.remaining).toString()} {row.unitLabel}{dec(row.remaining).lt(0)?" — Over authorization":""}</p>
   <details><summary className="cursor-pointer text-sm">Usage and revision history</summary><div className="overflow-x-auto mt-2"><table className="min-w-full text-sm"><thead><tr><th className="text-left">Service date</th><th className="text-right">{row.unitLabel}</th><th className="text-left px-3">Completion evidence / reason</th><th>Correction</th></tr></thead><tbody>{row.events.map(entry=><tr key={entry.id} className="border-t border-[var(--color-rule)]"><td className="py-2">{entry.serviceDate}</td><td className="text-right tnum">{dec(entry.quantity).toString()}</td><td className="px-3">{entry.evidence}<span className="block text-xs">{entry.reason}</span></td><td>{entry.reversesEventId?"Reversal":row.events.some(other=>other.reversesEventId===entry.id)?"Reversed":<button className="btn btn-sm btn-ghost" type="button" onClick={()=>open(row,"reverse",entry.id)}>Reverse usage</button>}</td></tr>)}</tbody></table></div>{row.revisions.map(revision=><p key={revision.revision} className="mt-2 text-xs">Revision {revision.revision}: {String(revision.snapshot.authorized_quantity)} {String(revision.snapshot.unit_label)} · {String(revision.snapshot.start_date)} to {String(revision.snapshot.end_date)}. Superseded: {revision.reason}</p>)}</details>
  </article>)}
  {editing?<form key={`${editing.row?.id??"new"}-${editing.action}`} onSubmit={submit} className="rounded-lg bg-[var(--color-surface-muted)] p-4 space-y-3">
   <h3 className="font-semibold">{editing.action==="create"?"New quantity authorization":editing.action==="revise"?"Revise authorization":editing.action==="consume"?"Record verified completed quantity":"Reverse an incorrect usage record"}</h3>
   {editing.action==="create"||editing.action==="revise"?<div className="grid gap-3 sm:grid-cols-2">
    {!editing.row?<label className="text-xs font-semibold">Program<select required name="programId" className="select w-full mt-1"><option value="">Choose program</option>{programs.map(program=><option value={program.id} key={program.id}>{program.name}</option>)}</select></label>:null}
    <label className="text-xs font-semibold">Unit label<input required name="unitLabel" className="input w-full mt-1" defaultValue={editing.row?.unitLabel??"visits"} maxLength={40}/></label>
    <label className="text-xs font-semibold">Authorized quantity<input required name="authorized" className="input w-full mt-1" type="number" min="0" step="0.0001" defaultValue={editing.row?.authorized}/></label>
    <label className="text-xs font-semibold">Starts<input required name="startDate" className="input w-full mt-1" type="date" defaultValue={editing.row?.startDate}/></label>
    <label className="text-xs font-semibold">Ends / renewal boundary<input required name="endDate" className="input w-full mt-1" type="date" defaultValue={editing.row?.endDate}/></label>
   </div>:editing.action==="consume"?<div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Service date<input required name="serviceDate" type="date" className="input w-full mt-1" defaultValue={agencyDate()}/></label><label className="text-xs font-semibold">Completed {editing.row?.unitLabel}<input required name="quantity" className="input w-full mt-1" type="number" min="0.0001" step="0.0001"/></label><label className="text-xs font-semibold sm:col-span-2">Completion evidence reference<input required minLength={3} name="evidence" className="input w-full mt-1" placeholder="Signed visit record or completion document reference"/></label></div>:<p className="text-sm">The original remains in history. An equal negative quantity restores the remaining authorization.</p>}
   <label className="block text-xs font-semibold">Reason<input required minLength={5} name="reason" className="input w-full mt-1"/></label>
   <div className="flex justify-end gap-2"><button type="button" disabled={saving} className="btn btn-secondary" onClick={()=>setEditing(null)}>Cancel</button><button type="submit" disabled={saving} className="btn btn-primary">{saving?"Saving…":"Save quantity record"}</button></div>
  </form>:null}
 </section>;
}
