/**
 * Embeds the .sql migration files into a TypeScript module.
 *
 * Vercel's serverless bundle does not reliably include loose .sql files, so the
 * migration runner reads them from this generated module instead of the disk.
 * The .sql files under drizzle/ remain the single source of truth; this file is
 * a build artifact, regenerated by `prebuild` and `pretest`.
 *
 * Regenerate manually with:  npm run db:embed
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { normalizeMigrationSql } from "../src/lib/db/migration-checksum";

const DIR = join(process.cwd(), "drizzle");
const OUT = join(process.cwd(), "src", "lib", "db", "migrations.generated.ts");

const files = readdirSync(DIR)
  .filter((f) => f.endsWith(".sql"))
  .sort();

const entries = files.map((name) => {
  const sql = normalizeMigrationSql(readFileSync(join(DIR, name), "utf8"));
  return `  {\n    name: ${JSON.stringify(name)},\n    sql: ${JSON.stringify(sql)},\n  },`;
});

const contents = `// GENERATED FILE - do not edit by hand.
// Source: drizzle/*.sql   Regenerate: npm run db:embed
export interface EmbeddedMigration {
  name: string;
  sql: string;
}

export const MIGRATIONS: EmbeddedMigration[] = [
${entries.join("\n")}
];
`;

writeFileSync(OUT, contents);
console.log(`Embedded ${files.length} migration(s) into ${OUT}`);
